# -*- coding: utf-8 -*-
"""Davit_Atabekyan_project_3_11_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCNykdn1usQUoTzvn_2qRuES6IXo5co5
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPooling2D, Dropout, BatchNormalization
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import Adam, SGD
from tensorflow.keras.regularizers import l1, l2
from tensorflow.keras.callbacks import EarlyStopping

train_dir = '/content/drive/MyDrive/cropped_train_data'
valid_dir = '/content/drive/MyDrive/cropped_valid_data'
test_dir = '/content/drive/MyDrive/cropped_test_data'

train_datagen = ImageDataGenerator(rescale=1./255)
valid_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size = (224, 224),
    class_mode='categorical'
)

valid_data = valid_datagen.flow_from_directory(
    valid_dir,
    target_size=(224, 224),
    class_mode='categorical'
)

test_data = test_datagen.flow_from_directory(
    test_dir,
    target_size=(224, 224),
    class_mode='categorical'
)

vgg = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

for layer in vgg.layers:
  layer.trainable=False
vgg.summary()

model = Sequential([
    vgg,
    Flatten(),
    Dense(256, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(128, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(64, activation='relu', kernel_regularizer=l2(0.01)),
    Dense(10, activation='softmax', kernel_regularizer=l2(0.01))
])

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)
early_stop= EarlyStopping(monitor='val_loss', patience=5,restore_best_weights=True, mode='min')
model.fit(train_data, validation_data=valid_data, epochs=50, callbacks=[early_stop])
loss, acc = model.evaluate(test_data)
print(f'Test accuracy {acc:.2f}')

model.summary()

import numpy as np
y_pred_prob = model.predict(test_data)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true=test_data.classes
class_names=list(test_data.class_indices.keys())

import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

y_true_bin = label_binarize(y_true, classes=range(len(class_names)))

for i in range(10):
  plt.figure(figsize=(10, 8))
  fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_prob[:, i])
  roc_auc=auc(fpr, tpr)
  plt.plot(fpr, tpr, label=f'{class_names[i]} Auc={roc_auc:.2f}')

  plt.plot([0, 1], [0, 1], 'k--')
  plt.xlabel('False_positive_rate')
  plt.ylabel('True_positive_rate')
  plt.title(f'Rocs Curve for Class: {class_names[i]}')
  plt.legend()
  plt.grid(True)
  plt.show()

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

y_true_bin = label_binarize(y_true, classes=range(len(class_names)))

plt.figure(figsize=(10, 8))
for i in range(len(class_names)):
  fpr, tpr, _ = roc_curve(y_true_bin[:, i], y_pred_prob[:, i])
  roc_auc=auc(fpr, tpr)
  plt.plot(fpr, tpr, label=f'{class_names[i]} (Auc={roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel('False_positive_rate')
plt.ylabel('True_positive_rate')
plt.title('Rocs curves for each class')
plt.legend()
plt.grid()
plt.show()